import Head from "next/head";
import Image from "next/image";
// import { Inter } from '@next/font/google'
import axios from "axios";
import * as S from "../styles/Home";
import React, { useEffect, useState } from "react";
import Characters from './components/Characters'; 

// const inter = Inter({ subsets: ['latin'] })

function Home() {

const [characters, setCharacters ] = useState([]);
const primeiraUrl = 'https://rickandmortyapi.com/api/character'

  const fetchCharacters = (url) => {
    fetch("url")
      .then((response) => response.json())
      .then((data) => setCharacters(data))
      .catch((error) => console.log(error));
  };
console.log(characters,'');
  useEffect(() => {
    fetchCharacters(primeiraUrl);
  }, []);

  return (
    <div>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Rick and Morty</p>
<div>
  {/* <Characters characters={characters} /> */}
</div>


    </div>
  );
}

export default Home;

// fetch('https://rickandmortyapi.com/api/character')
// .then(response => response.json())
// .then(data => console.log(data))
// .catch(error => console.log(error))
