import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import * as S from "../styles/Home";
import React, { useEffect, useState } from "react";
import Characters from "../components/Characters";
import Paginas from "../components/Paginas";

function Home() {
  const [characters, setCharacters] = useState([]);
  const [info, setInfo] = useState({});
  const [name, setName] = useState("");

  const primeiraUrl = "https://rickandmortyapi.com/api/character?page=1";

  const getCharacters = () => {
    axios.get(primeiraUrl)
      .then((res) => {
        setCharacters(res.data.results);
        setInfo(res?.data.info);
        console.log(info, "infooooo");
      })
  }
  useEffect(() => {
    getCharacters(primeiraUrl)
  }, []);

  const onPrevious = () => {
    getCharacters(info?.prev);
  };
  const onNext = () => {
    getCharacters(info?.next);
  };


  return (
    <S.container>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.Title>Rick and Morty</S.Title>

      <S.Inp
        onChange={(e) => setName(e.target.value)}
        value={name}
        placeholder="Procure aqui um personagem"
      />

      <div>
        <Paginas
          prev={info?.prev}
          next={info?.next}
          onPrevious={onPrevious}
          onNext={onNext}
        />
        <Characters characters={characters} name ={name} />
        <Paginas
          prev={info?.prev}
          next={info?.next}
          onPrevious={onPrevious}
          onNext={onNext}
        />
      </div>
    </S.container>
  );
}

export default Home;
